### PR TITLE
WIP: Updates for 8.0.1

### PR DESCRIPTION
**Pull request by hmhealey**
I haven't been able to actually test this since the servers are having a fit, but this fixes every error I came across so far since 8.0.1 released.

Change reference: https://wow.gamepedia.com/Patch_8.0.1/API_changes

### CODE REVIEW

**Comment by Stmdotcom** [comment]
One missing thing I've noticed so far (For druid at least) is the small on bar icons (Hots timers) arn't showing

I've managed to fix the above. Any instance of UnitAura the second return value as been removed. So for instance 

`local bName,_,iTexture,bCount,_,_,expirationTime, caster,_,_,spellID = UnitAura(xUnit, k, "HELPFUL");`

Becomes

`local bName,iTexture,bCount,_,_,expirationTime, caster,_,_,spellID = UnitAura(xUnit, k, "HELPFUL");`

Note the removal of the second _ that was used to 'skip' the assign (Not sure what this is called in LUA)

**Comment by Stmdotcom** [comment]
Also as an FYI this post

https://us.battle.net/forums/en/wow/topic/20762318007 

Seems to cover a lot of changes that arn't in the wowpedia document

**Comment by jbarnes** [comment]
Currently live testing @Stmdotcom master branch (this PR) as a Paladin.

- Has fixed health bars not correctly reflecting players actual health
- Tank, Healer, Damage Icons are now correctly reflected and in there intended position
- Doesn't appear to be showing buff icons (Beacon of Light/Faith)
- The frame alignment would get out of sync on instance loads/new zone loads, no longer occurring
- Healbot no longer crashing due to substantial amount of errors

**Note**: HB 7.3.5 would almost instantly crash due to errors, I tested with a download put on the healbot forums for 8.0.1 by 'Strife' this was partly functional, but had all of the problems I listed above.

+1 for this PR, other than the patch number being incorrect.

**Comment by Stmdotcom** [comment]
I just did a raid with this PR and the UnitAura fix I mentioned above. The LUA bugs I encountered in the raid where:

`352x HealBot\HealBot-8.1.0.lua:3588: attempt to concatenate field 'spellId' (a boolean value)` 
I suppressed the error by removing this block. Likely this is caused but UnitDebuff, this needs the same fix as UnitAura above, where the second return param has been removed

`78x HealBot\HealBot-8.1.0.lua:5598: attempt to call global 'GetPlayerMapPosition' (a nil value)`
I suppressed the error by removing this block. But I assume the fix is changing to use C_Map.GetPlayerMapPosition I will test this when I have more time

**Comment by hmhealey** [comment]
One other thing I haven't had a chance to fix yet with this branch is that there's a call to the removed function `GetCurrentMapContinent` in HealBot_Action.lua at line 4286. The closest I can find to an exact replacement for it is using `local mapInfo = C_Map.GetMapInfo(C_Map.GetBestMapForUnit("player"))` and then recursing with `mapInfo = C_Map.GetMapInfo(mapInfo.parentMapID)` until `mapInfo.mapType==2` to get to the continent's map.

**Comment by garemoko** [comment]
I tested hmhealey:master on Holy priest through an LFG Heroic Dungeon and it worked fine except for the warning about out of date version number and the issue with spell icons (specifically 'renew' in my case) not displaying. 

I then applied the fixes as suggested [above](https://github.com/davidmarshall15/Healbot/pull/37#issuecomment-405823086) and that seems to have resolved the spell icons issue from testing with casting renew on myself in my class hall.

On that basis, and since I don't see a PR for @Stmdotcom's suggested changes, I plan to fork hmhealey:master and PR those changes into this PR.

**Comment by garemoko** [comment]
I also opened a PR to hmhealey:master to fix the core healbot and the tips addon to use the right interface number. With that version they will run with out of date addons disabled.

**Comment by garemoko** [comment]
Note: the title of the PR says 8.1 but the current version of wow is 8.0.1

**Comment by n1ghty** [comment]
- The mappings in HealBot_Localization.en.lua should now be
```
    HEALBOT_ZONE_AB                         = C_Map.GetMapInfo(93).name or "Arathi Basin";
    HEALBOT_ZONE_AV                         = C_Map.GetMapInfo(91).name or "Alterac Valley";
    HEALBOT_ZONE_ES                         = C_Map.GetMapInfo(112).name or "Eye of the Storm";
    HEALBOT_ZONE_IC                         = C_Map.GetMapInfo(169).name or "Isle of Conquest";
    HEALBOT_ZONE_SA                         = C_Map.GetMapInfo(171).name or "Strand of the Ancients";
```


- In HealBot.lua:
```
function HealBot_Register_Events()
...
    --    HealBot:RegisterEvent("UNIT_MAXMANA")
```
should be 
`        HealBot:RegisterEvent("UNIT_MAXPOWER")`
now.
- and
```
function HealBot_Register_Mana()
    HealBot:RegisterEvent("UNIT_MANA")
```
should be
```
function HealBot_Register_Mana()
    HealBot:RegisterEvent("UNIT_POWER_UPDATE")
```

- and
```
function HealBot_getUnitCoords(unit)
--    if UnitIsPlayer(unit) then
--        local x, y = GetPlayerMapPosition(unit);
--        if x and y and x > 0 and y > 0 then
--            return x, y
--        end
--    end
```
should be
```
function HealBot_getUnitCoords(unit)
    if UnitIsPlayer(unit) then
        local mapID = C_Map.GetBestMapForUnit(unit)
        local x, y = C_Map.GetPlayerMapPosition(mapID, unit)
        if x and y and x > 0 and y > 0 then
            return x, y
        end
    end
```

**Comment by hmhealey** [comment]
@garemoko I just merged one of your PRs, but it looks like @davidmarshall15 has started to update his code separately, so I think I'm going to break this branch down into separate PRs to avoid conflicting with things that he's already fixed. You'll probably want to resubmit yours against this repository instead

**Comment by hmhealey** [comment]
Closing this PR in favour of smaller, self-contained ones. If anyone wants to keep using the latest version of the addon with these additional fixes applied, I'll be maintaining https://github.com/hmhealey/Healbot for the time being until the addon is fully updated.

**Pull request closed without merging**
